### ISSUE TITLE
Error When Exporting List of Instances Without Material

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-opencutlist-sketchup-extension#135]
When trying to export a list of instances with no material, it creates the csv export file but fails to write to it.

Here is the console output:

```
undefined local variable or method `hide_untyped_material_dimensions' for #<Ladb::OpenCutList::CutlistExportWorker:0x0001cece436ec8>
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:247:in `block (4 levels) in run'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:244:in `each'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:244:in `block (3 levels) in run'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:241:in `each'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:241:in `block (2 levels) in run'
C:/Program Files/SketchUp/SketchUp 2017/Tools/RubyStdLib/csv.rb:1157:in `generate'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:80:in `block in run'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:79:in `open'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_export_worker.rb:79:in `run'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:103:in `export_command'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:24:in `block in setup_commands'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:193:in `call'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:193:in `execute_command'
C:/Data/opencutlist/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:424:in `block in create_dialog'
SketchUp:1:in `call'
```

**Comment by bbeaulant** [comment]
Fixed, thank you :)
