### ISSUE TITLE
Error when cutting

### ISSUE THREAD

**Issue by DamirGatin** [lairdubois/lairdubois-opencutlist-sketchup-extension#633]
[clippy.rb:180] : can't load C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/../../../bin/x86/lib/Clippy.dll
Error: 
#<NameError: undefined local variable or method `c_clear_subjects' for Ladb::OpenCutList::Clippy:Module>
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:280:in `_clear'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/lib/clippy/clippy.rb:30:in `execute_difference'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:131:in `block (2 levels) in run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:129:in `each'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:129:in `block in run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:127:in `each'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:127:in `each_with_index'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:127:in `run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:65:in `_compute_part_projection_def'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram2d_worker.rb:293:in `block (2 levels) in run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram2d_worker.rb:269:in `each'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram2d_worker.rb:269:in `block in run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram2d_worker.rb:243:in `each'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/worker/cutlist/cutlist_cuttingdiagram2d_worker.rb:243:in `run'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:288:in `group_cuttingdiagram2d_advance_command'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/controller/cutlist_controller.rb:84:in `block in setup_commands'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:726:in `execute_command'
C:/Users/Димарик/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/ladb_opencutlist/ruby/plugin.rb:1070:in `block in create_tabs_dialog'

**Comment by DamirGatin** [comment]
What could be causing this?

**Comment by mobilarte** [comment]
It is a problem caused by the loading of the DLL Clippy.dll when the path of the user contains non-ascii characters. We are working on a fix, but it seems very tedious to fix it for both windows and mac.

**Comment by bbeaulant** [comment]
@DamirGatin , currently the workaround is to Hide Shape of Parts in Cutting diagram settings to avoid this error.

**Comment by bbeaulant** [comment]
Hi,
This error is fixed in the last 6.1.0 release.
