### ISSUE TITLE
Error when packing calculating using new cutting diagram code

### ISSUE THREAD

**Issue by mauriciobellon** [lairdubois/lairdubois-opencutlist-sketchup-extension#662]
```
-------------------------------------------------------------
Please email the following error to opencutlist@lairdubois.fr
-------------------------------------------------------------
OpenCutList 7.0.0-dev (build:202408221656) / en - SketchUp 24.0.553 - win
#<Fiddle::DLError: cannot find the function: c_boolean_op()>
C:/Program Files/SketchUp/SketchUp 2024/Tools/RubyStdLib/fiddle/import.rb:297:in `import_function'
C:/Program Files/SketchUp/SketchUp 2024/Tools/RubyStdLib/fiddle/import.rb:170:in `extern'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/wrapper.rb:86:in `block in _load_lib'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/wrapper.rb:85:in `each'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/wrapper.rb:85:in `_load_lib'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/wrapper.rb:23:in `available?'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/common/common_drawing_projection_worker.rb:38:in `run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/helper/part_drawing_helper.rb:78:in `_compute_part_projection_def'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:188:in `block in run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:226:in `block in run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:220:in `each'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:220:in `run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:351:in `group_packing_start_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:102:in `block in setup_commands'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:702:in `execute_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:1053:in `block in create_tabs_dialog'
-------------------------------------------------------------
To resolve this issue, try installing the Microsoft Visual C++ Redistributable available here :
https://aka.ms/vs/17/release/vc_redist.x64.exe
-------------------------------------------------------------
-------------------------------------------------------------
Please email the following error to opencutlist@lairdubois.fr
-------------------------------------------------------------
OpenCutList 7.0.0-dev (build:202408221656) / en - SketchUp 24.0.553 - win
#<RuntimeError: 'Packy' lib not found : C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/bin/win/lib/Packy.dll>
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/wrapper.rb:62:in `_load_lib'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/packy/packy.rb:43:in `optimize_start'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:275:in `run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:351:in `group_packing_start_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:102:in `block in setup_commands'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:702:in `execute_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:1053:in `block in create_tabs_dialog'
-------------------------------------------------------------
To resolve this issue, try installing the Microsoft Visual C++ Redistributable available here :
https://aka.ms/vs/17/release/vc_redist.x64.exe
-------------------------------------------------------------
Error: #<NoMethodError: undefined method `c_optimize_start' for Ladb::OpenCutList::Fiddle::Packy:Module>
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/lib/fiddle/packy/packy.rb:50:in `optimize_start'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/worker/cutlist/cutlist_packing_worker.rb:275:in `run'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:351:in `group_packing_start_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/controller/cutlist_controller.rb:102:in `block in setup_commands'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:702:in `execute_command'
C:/Users/Mauricio/Code/lairdubois-opencutlist-sketchup-extension/src/ladb_opencutlist/ruby/plugin.rb:1053:in `block in create_tabs_dialog'

```

Don't know if you are aware, but in Windows it is not going nice as in your YouTube video... haha

Tried to reinstall Microsoft Visual C++ Redistributable didn't solve.

I notice that this message repeats for every part that is expected to be in the diagram.

after theses messages the OCL freezes.

**Comment by bbeaulant** [comment]
Yes, I have intentionally not yet published the compiled DLLs on the repository.
Please, contact me by email through the "Report a bug" button to communicate on new features.
